name: CI

on:
  pull_request:
    branches:
      - main
      - "release/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Build release
        env:
          SCCACHE_GHA_ENABLED: "true"
          SCCACHE_GHA_CACHE_PREFIX: "sccache-windows"
          RUSTC_WRAPPER: "sccache"
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Calculate and display binary size
        shell: pwsh
        run: |
          $size = (Get-Item "target/x86_64-pc-windows-msvc/release/gittop.exe").Length / 1MB
          $sizeFormatted = "{0:N2} MB" -f $size
          echo "### Binary Size Statistics :bar_chart:" >> $env:GITHUB_STEP_SUMMARY
          echo "| Artifact | Size |" >> $env:GITHUB_STEP_SUMMARY
          echo "| :--- | :--- |" >> $env:GITHUB_STEP_SUMMARY
          echo "| gittop.exe | $sizeFormatted |" >> $env:GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: target/x86_64-pc-windows-msvc/release/gittop.exe

      - uses: kesin11/actions-timeline@v2
